### PR TITLE
Rename pctl to kivo

### PR DESCRIPTION
**Pull request by aclevername**
### Description

Almost all code changes are done. When the repo URL is changed we fix the following:
- Fix references to `pctl-test-repo`
- Revert https://github.com/weaveworks/pctl/pull/323/commits/abb88a3a9d4c96af77c4dae83623829ba074cee0
- Remove https://github.com/aclevername/pctl/blob/45f2c6d1c39e365074934d29126f66217e65db6d/go.mod#L36-L37
- Rename the go module https://github.com/weaveworks/pctl/blob/main/go.mod#L1

Then we are good to merge :smile: 

Also sneaked in a couple dependency bumps:
https://github.com/weaveworks/pctl/pull/325
https://github.com/weaveworks/pctl/pull/326
https://github.com/weaveworks/pctl/pull/327
https://github.com/weaveworks/pctl/pull/328
https://github.com/weaveworks/pctl/pull/324

### Checklist
- [ ] Added tests that cover your change
- [ ] Added/modified documentation as required (such as the `README.md`)
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] Added a `kind` label to the PR (e.g. `kind/feature`)

### CODE REVIEW

**Review by Callisto13 — APPROVED** [review]
i am NOT reading 73 files, so i am gonna trust you got it all

_tip 5 in the "How to do Code Reviews properly" handbook_

**Comment by aclevername** [comment]
> i am NOT reading 73 files, so i am gonna trust you got it all
> 
> _tip 5 in the "How to do Code Reviews properly" handbook_

:bow:

**Comment by Skarlso** [comment]
Should probably also rename https://github.com/weaveworks/pctl-test-repo. And then in the corresponding integration test yaml file the repository name.

**Review by Skarlso — CHANGES_REQUESTED** [review]
Also update `.goreleaser.yml` for generating the correct binary name and the github workflows. Also `integration_installation_test.go` and `integration_docgen_test.go` still has

```go
var _ = Describe("PCTL", func() {
```

And update the environment property `PCTL_TEST_REPOSITORY_URL`.

Further question: What about the docker images?

**Comment by aclevername** [comment]
> Also update `.goreleaser.yml` for generating the correct binary name and the github workflows. Also `integration_installation_test.go` and `integration_docgen_test.go` still has
> 
> ```go
> var _ = Describe("PCTL", func() {
> ```
> 
> And update the environment property `PCTL_TEST_REPOSITORY_URL`.
> 
> Further question: What about the docker images?

Damn `ripgrep` ignoring dotfiles! Good spot will update

**Comment by aclevername** [comment]
> Should probably also rename https://github.com/weaveworks/pctl-test-repo. And then in the corresponding integration test yaml file the repository name.

already'd referenced at the top of the PR :wink: 



> Also update `.goreleaser.yml` for generating the correct binary name and the github workflows. Also `integration_installation_test.go` and `integration_docgen_test.go` still has
> 
> ```go
> var _ = Describe("PCTL", func() {
> ```

> And update the environment property `PCTL_TEST_REPOSITORY_URL`.

I'll add to the PR description, we might have to do this later (we already have a lot of corp requests open!)

> Further question: What about the docker images?

Thats for the Pr in `profiles`, not here :smile:

**Review by Skarlso — APPROVED** [review]

**Comment by Himangini** [comment]
why this one has skip-release-notes label? 🤔

**Comment by Himangini** [comment]
Closing this off since we no longer need this, sorry :(

**Pull request closed without merging**
