### PR TITLE
Use GITHUB_TOKEN rather than GIT_TOKEN

### LINKED ISSUE #247: Rename `$GIT_TOKEN` to match flux's `$GITHUB_TOKEN`
**What feature/behavior/change do you want?**

This is a bit nit but it would be nice to rename `$GIT_TOKEN` to match flux's `$GITHUB_TOKEN` if possible.

**Why do you want this feature?**

I got this error:
```
pctl add \
  --profile-url https://www.github.com/nikimanoledaki/demo-profile \
  --create-pr \
  --pr-repo nikimanoledaki/demo-profile \
 --config-map configmap.yaml
generating profile installation from source: repository https://www.github.com/nikimanoledaki/demo-profile, path: . and branch main
installation completed successfully
Creating a PR to repo nikimanoledaki/demo-profile with base main and branch pctl-profile-4d1752
failed to create scm client: failed to create scm client: No Git OAuth token specified for $GIT_TOKEN
```

I set it to `$GITHUB_TOKEN`, which I had set as part of my [flux config](https://fluxcd.io/docs/get-started/#prerequisites). If we could rename this to match the flux env var it will be one less step when using `pctl`! :) 

## Implementation
We need to change how we build the client to not use the environment, as the library uses `GIT_TOKEN`
https://github.com/weaveworks/pctl/blob/31164f3f2c9fe6271ba07f2c0347f2f5ff33d21c/pkg/git/scm_git.go#L31-L42

### PR DESCRIPTION
**Pull request by aclevername**
### Description

Closes #247 

Docs PR: https://github.com/weaveworks/profiles/pull/285

### Checklist
- [ ] Added tests that cover your change
- [ ] Added/modified documentation as required (such as the `README.md`)
- [ ] Made sure the title of the PR is a good description that can go into the release notes
- [ ] Added a `kind` label to the PR (e.g. `kind/feature`)

### CODE REVIEW

**Comment by Callisto13** [comment]
THANK YOU

**Comment by Callisto13** [comment]
but wait, am I blind? where is the "rather than" happening? all I can see is new code, nothing being replaced

**Comment by aclevername** [comment]
The library we used defaulted to GIT_TOKEN, we changed how we build the client to now manually pass in the credentials

**Comment by Callisto13** [comment]
I seeeeee

**Review by Callisto13 — APPROVED** [review]

**Pull request merged**
