### PR TITLE
Rename `--profile-url` to `--profile-repo-url`

### LINKED ISSUE #246: Rename `--profile-url` to `--profile-repo-url `
**What feature/behavior/change do you want?**

It would be nice if we could rename `--profile-url` to `--profile-repo-url `. 

**Why do you want this feature?**

The wording of `--profile-url` is a bit misleading: intuitively, it seems to refer to the full URL to the profile e.g. `https://github.com/nikimanoledaki/demo-profile/blob/main/profile.yaml`, but it actually refers to the repo containing the profile, e.g. `https://github.com/nikimanoledaki/demo-profile`

### PR DESCRIPTION
**Pull request by nikimanoledaki**
### Description

closes #246 
doc changes in https://github.com/weaveworks/profiles/pull/277

- Replacing `--profile-repo` with `--profile-repo-url` because it's better at conveying that it refers to the URL needed to clone the profile, not the full URL that leads to the profile.yaml itself.

### Checklist
- [ ] Added tests that cover your change
- [x] Added/modified documentation as required (such as the `README.md`)
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] Added a `kind` label to the PR (e.g. `kind/feature`)

### CODE REVIEW

**Comment by Callisto13** [comment]
Is `profile-repo-url` any clearer? Given we have at least 2 repos in play here, could it be confusing? Could users think it is their repo where they keep their profiles? 🤷‍♀️

**Comment by Callisto13** [comment]
Are we changing the other `--profile-x` flags too?

**Comment by aclevername** [comment]
> Is `profile-repo-url` any clearer? Given we have at least 2 repos in play here, could it be confusing? Could users think it is their repo where they keep their profiles?

I think it fixes some of the confusion for sure. from the linked issue https://github.com/weaveworks/pctl/issues/246:

> The wording of --profile-url is a bit misleading: intuitively, it seems to refer to the full URL to the profile e.g. https://github.com/nikimanoledaki/demo-profile/blob/main/profile.yaml, but it actually refers to the repo containing the profile, e.g. https://github.com/nikimanoledaki/demo-profile

**Review by aclevername — APPROVED** [review]
LGTM

**Comment by nikimanoledaki** [comment]
In `pctl add`, all flags starting with `--profile-` (`--profile-branch`, `--profile-path`, `--profile-repo-url`) are referring to the source repo/location of the profile to be added. 

The flags that refer to the destination repo/location are `--out` and all the flags that start with `--pr-` since they refer to the GitOps repo.

I think this distinction helps the UX! 

We could organise the flags in `pctl add --help` into categories to reduce the confusion even more.

**Pull request merged**
